### ISSUE TITLE
Is there any python wrapper for this project 

### ISSUE THREAD

**Issue by itsmedralpha** [roboception/rc_genicam_3dviewer#1]
I am trying to use pointcloud data of roboception without using ROS, so is there any way we can save the pointcloud data as pcd or ply so we can do further process

**Comment by itsmedralpha** [comment]
or if there any other python package available to get the camera image and parameters continuously without using ROS

**Comment by heikohimu** [comment]
You can use the command line tool gc_pointcloud from the rc_genicam_api package, i.e. https://github.com/roboception/rc_genicam_api/releases/tag/v2.5.12

A PLY is also contained in the depth snapshot that you can download from the depth image page of the Web GUI.

Both is rather slow since it needs to setup everything just for one shot. If you need it faster, then you can have a look into the source code of rc_pointcloud and implement it yourself based on the rc_genicam_api.
